project_id = "tkppayricdwsogopxxzp"

[functions.web-scrape]
verify_jwt = false

[functions.google-search]
verify_jwt = false

[functions.brave-search]
verify_jwt = false

[functions.weather]
verify_jwt = false

[functions.time]
verify_jwt = false

[functions.api-call]
verify_jwt = false

[functions.run-agent]
verify_jwt = false

[functions.run-agent-anthropic]
verify_jwt = false

[functions.run-agent-xai]
verify_jwt = false

[functions.run-nano]
verify_jwt = false

[functions.get-elevenlabs-voices]
verify_jwt = false

[functions.elevenlabs-tts]
verify_jwt = false

[functions.send-email]
verify_jwt = false

[functions.github-fetch]
verify_jwt = false

[functions.pronghorn-post]
verify_jwt = false

[functions.free-agent]
verify_jwt = false

[functions.external-db]
verify_jwt = false
